import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import NavBar from '@/components/NavBar/page'
import Footer from '@/components/Footer/page'

export const metadata = {
  title: 'StyleMaven Shopping App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body>
          <NavBar/> 
          {children}
          <Footer/>
        </body>
      </ClerkProvider> 
    </html>
  )
}
